-- Galeasso Federico 5L - Convention DDL

-- DROP DATABASE IF EXISTS Galeasso_Convention;
-- CREATE DATABASE IF NOT EXISTS Galeasso_Convention;
USE Galeasso_Convention;

CREATE TABLE IF NOT EXISTS UTENTE (
	IDUtente INT NOT NULL AUTO_INCREMENT,
	Email VARCHAR(50) NOT NULL,
	Password VARCHAR(64) NOT NULL,
	Ruolo VARCHAR(20) NOT NULL,
	PRIMARY KEY (IDUtente)
);

CREATE TABLE IF NOT EXISTS AZIENDA (
	RagioneSocialeAzienda VARCHAR(50) NOT NULL,
	IndirizzoAzienda VARCHAR(30) NOT NULL,
	TelefonoAzienda VARCHAR(20) NOT NULL,
	PRIMARY KEY (RagioneSocialeAzienda)
);

CREATE TABLE IF NOT EXISTS RELATORE (
	IDRel INT NOT NULL AUTO_INCREMENT,
	CognomeRel VARCHAR(25) NOT NULL,
	MailRel VARCHAR(30) NOT NULL,
	NomeRel VARCHAR(25) NOT NULL,
	RagioneSocialeAzienda VARCHAR(50) NOT NULL,
	IDUtente INT NOT NULL,
	FOREIGN KEY (RagioneSocialeAzienda) REFERENCES AZIENDA(RagioneSocialeAzienda),
	FOREIGN KEY (IDUtente) REFERENCES UTENTE(IDUtente),
	PRIMARY KEY (IDRel)
);

CREATE TABLE IF NOT EXISTS PIANO (
	Numero INT NOT NULL,
	PRIMARY KEY (Numero)
);

CREATE TABLE IF NOT EXISTS SALA (
	NomeSala VARCHAR(20) NOT NULL,
	NpostiSala INT NOT NULL,
	Numero INT NOT NULL,
	FOREIGN KEY (Numero) REFERENCES PIANO(Numero),
	PRIMARY KEY (NomeSala)
);

CREATE TABLE IF NOT EXISTS PARTECIPANTE (
	IDPart INT NOT NULL AUTO_INCREMENT,
	CognomePart VARCHAR(25) NOT NULL,
	NomePart VARCHAR(25) NOT NULL,
	MailPart VARCHAR(30) NOT NULL,
	TipologiaPart VARCHAR(30) NOT NULL,
	IDUtente INT NOT NULL,
	FOREIGN KEY (IDUtente) REFERENCES UTENTE(IDUtente),
	PRIMARY KEY (IDPart)
);

CREATE TABLE IF NOT EXISTS SPEECH (
	IDSpeech INT NOT NULL AUTO_INCREMENT,
	Titolo VARCHAR(30) NOT NULL,
	Argomento VARCHAR(20) NOT NULL,
	PRIMARY KEY (IDSpeech)
);

CREATE TABLE IF NOT EXISTS PROGRAMMA (
	IDProgramma INT NOT NULL AUTO_INCREMENT,
	FasciaOraria VARCHAR(20) NOT NULL,
	IDSpeech INT NOT NULL,
	NomeSala VARCHAR(20) NOT NULL,
	FOREIGN KEY (IDSpeech) REFERENCES SPEECH(IDSpeech),
	FOREIGN KEY (NomeSala) REFERENCES SALA(NomeSala),
	PRIMARY KEY (IDProgramma)
);

CREATE TABLE IF NOT EXISTS RELAZIONA (
	IDRel INT NOT NULL AUTO_INCREMENT,
	IDProgramma INT NOT NULL,
	FOREIGN KEY (IDRel) REFERENCES RELATORE(IDRel),
	FOREIGN KEY (IDProgramma) REFERENCES PROGRAMMA(IDProgramma),
	PRIMARY KEY (IDRel,IDProgramma)
);

CREATE TABLE IF NOT EXISTS SCEGLIE (
	IDPart INT NOT NULL AUTO_INCREMENT,
	IDProgramma INT NOT NULL,
	FOREIGN KEY (IDPart) REFERENCES PARTECIPANTE(IDPart),
	FOREIGN KEY (IDProgramma) REFERENCES PROGRAMMA(IDProgramma),
	PRIMARY KEY (IDPart,IDProgramma)
);