-- Galeasso Federico 5L 25/02/2024 - DDL Viaggi SQL

DROP DATABASE Viaggi;
CREATE DATABASE IF NOT EXISTS Viaggi;
USE Viaggi;

CREATE TABLE IF NOT EXISTS Destinazioni (
	CodDest INT NOT NULL PRIMARY KEY,
	Denominazione VARCHAR(50) NOT NULL,
	Moneta VARCHAR(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS Clienti (
	CodCli INT NOT NULL PRIMARY KEY,
	CognomeCli VARCHAR(50) NOT NULL,
	NomeCli VARCHAR(50) NOT NULL,
	IndirizzoCli VARCHAR(100) NOT NULL,
	TelCli VARCHAR(15) NOT NULL
);

CREATE TABLE IF NOT EXISTS TourOperator (
	CodTour INT NOT NULL PRIMARY KEY,
	NomeTour VARCHAR(50) NOT NULL,
	IndirizzoTour VARCHAR(100) NOT NULL,
	TelTour VARCHAR(15) NOT NULL
);

CREATE TABLE IF NOT EXISTS Pacchetti (
	CodPacch INT NOT NULL PRIMARY KEY,
	Modalita VARCHAR(50) NOT NULL,
	Prezzo DECIMAL(10,2) NOT NULL,
	CodDest INT NOT NULL,
	CodTour INT NOT NULL,
	FOREIGN KEY (CodDest) REFERENCES Destinazioni(CodDest),
	FOREIGN KEY (CodTour) REFERENCES TourOperator(CodTour)
);

CREATE TABLE IF NOT EXISTS Acquisti (
	CodAcq INT NOT NULL PRIMARY KEY,
	CodCli INT NOT NULL,
	CodPacch INT NOT NULL,
	DataAcquisto DATE NOT NULL,
	FOREIGN KEY (CodCli) REFERENCES Clienti(CodCli),
	FOREIGN KEY (CodPacch) REFERENCES Pacchetti(CodPacch)
);