CREATE DATABASE IF NOT EXISTS Mercantile;

USE Mercantile;

CREATE TABLE IF NOT EXISTS NAVI(
	CodiceNave INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NomeNave VARCHAR(30) NULL, 
	Stazza INT NULL, 
	Lunghezza INT NULL, 
	AnnoDiCostruzione DATE NULL, 
	PotenzaMotori INT NULL
);

CREATE TABLE IF NOT EXISTS PORTI(
	CodicePorto INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
	NomePorto VARCHAR(30) NULL
);

CREATE TABLE IF NOT EXISTS PERSONALE(
	CodiceFiscale INT NOT NULL PRIMARY KEY, 
	NomePersonale VARCHAR(30) NOT NULL, 
	CognomePersonale VARCHAR(30) NOT NULL, 
	LuogoDiNascita VARCHAR(30) NOT NULL, 
	DataDiNascita DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS VIAGGI(
	ID_viaggio INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
	DataPartenza DATE NOT NULL, 
	OraPartenza TIME NOT NULL, 
	DataArrivo DATE NOT NULL, 
	OraArrivo TIME NOT NULL, 
	PesoTotale INT NOT NULL, 
	CodiceNave INT NOT NULL, 
	CodicePorto INT NOT NULL,
	FOREIGN KEY(CodiceNave) REFERENCES NAVI(CodiceNave),
	FOREIGN KEY(CodicePorto) REFERENCES PORTI(CodicePorto)
);

CREATE TABLE IF NOT EXISTS MESSAGGI(
	ID_messaggio INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
	Latitudine VARCHAR(170) NOT NULL, 
	Longitudine VARCHAR(170) NOT NULL, 
	Direzione VARCHAR(50) NOT NULL, 
	Velocità INT NOT NULL, 
	DataMessagio DATE NOT NULL, 
	OraMessagio TIME NOT NULL, 
	NoteDelCapitano VARCHAR(30) NOT NULL, 
	ID_viaggio INT NOT NULL,
	FOREIGN KEY(ID_viaggio) REFERENCES VIAGGI(ID_viaggio)
);

CREATE TABLE IF NOT EXISTS PRESENTE(
	CodiceFiscale INT NOT NULL, 
	ID_viaggio INT NOT NULL, 
	Ruolo VARCHAR(30) NOT NULL,
	FOREIGN KEY(CodiceFiscale) REFERENCES PERSONALE(CodiceFiscale),
	FOREIGN KEY(ID_viaggio) REFERENCES VIAGGI(ID_viaggio),
	PRIMARY KEY(CodiceFiscale, ID_viaggio)
);
