-- Galeasso Federico 5L 13/2/2024 - Compito Orvieto SQL

CREATE DATABASE IF NOT EXISTS Orvieto;

USE Orvieto;

CREATE TABLE IF NOT EXISTS Direttore(
	ID_D INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NOME_D VARCHAR(20) NOT NULL,
	COG_D VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS Orchestra(
	ID_OA INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NOME_OA VARCHAR(20) NOT NULL,
	ID_D INT NOT NULL,
	FOREIGN KEY(ID_D) REFERENCES Direttore(ID_D)
);

CREATE TABLE IF NOT EXISTS Orchestrale(
	MAT_OE VARCHAR(5) NOT NULL PRIMARY KEY,
	COG_OE VARCHAR(20) NOT NULL,
	NOME_OE VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS Strumento(
	ID_ST INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NOME_ST VARCHAR(20) NOT NULL,
	MAT_OE VARCHAR(5) NOT NULL,
	FOREIGN KEY(MAT_OE) REFERENCES Orchestrale(MAT_OE)
);

CREATE TABLE IF NOT EXISTS Sala(
	ID_SA INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NOME_SA VARCHAR(20) NOT NULL,
	CAPIE_SA INT NOT NULL
);

CREATE TABLE IF NOT EXISTS Concerto(
	ID_C INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	DESC_C TEXT NOT NULL,
	TIT_C VARCHAR(15) NOT NULL,
	ID_OA INT NOT NULL,
	FOREIGN KEY(ID_OA) REFERENCES Orchestra(ID_OA)
);

CREATE TABLE IF NOT EXISTS Pezzo(
	ID_P INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	TIT_P VARCHAR(15) NOT NULL
);

CREATE TABLE IF NOT EXISTS Autore(
	ID_A INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NOME_A VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS Tenuto(
	ID_C INT NOT NULL,
	ID_SA INT NOT NULL,
	DATA_C DATE NOT NULL,
	FOREIGN KEY(ID_C) REFERENCES Concerto(ID_C),
	FOREIGN KEY(ID_SA) REFERENCES Sala(ID_SA),
	PRIMARY KEY (ID_C, ID_SA)
);

CREATE TABLE IF NOT EXISTS Composta(
	ID_OA INT NOT NULL,
	MAT_OE VARCHAR(5) NOT NULL,
	FOREIGN KEY(ID_OA) REFERENCES Orchestra(ID_OA),
	FOREIGN KEY(MAT_OE) REFERENCES Orchestrale(MAT_OE),
	PRIMARY KEY (ID_OA, MAT_OE)
);

CREATE TABLE IF NOT EXISTS Formato(
	ID_C INT NOT NULL,
	ID_P INT NOT NULL,
	FOREIGN KEY(ID_C) REFERENCES Concerto(ID_C),
	FOREIGN KEY(ID_P) REFERENCES Pezzo(ID_P),
	PRIMARY KEY (ID_C, ID_P)
);

CREATE TABLE IF NOT EXISTS Scritto(
	ID_P INT NOT NULL,
	ID_A INT NOT NULL,
	FOREIGN KEY(ID_P) REFERENCES Pezzo(ID_P),
	FOREIGN KEY(ID_A) REFERENCES Autore(ID_A),
	PRIMARY KEY (ID_P, ID_A)
);